[package]
name = "preprocessing"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.23", features = ["derive"] }
flate2 = "1.0.35"
shakmaty = "0.27.2"
tar = "0.4.43"
