[project]
name = "training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aqtp>=0.8.2",
    "chex>=0.1.88",
    "flax>=0.10.2",
    "jax>=0.4.38",
    "optax>=0.2.4",
    "orbax>=0.1.9",
]
